name: "dbt_btc"
version: "1.0.0"
config-version: 2

profile: "dbt_btc"

model-paths:
  - "models"

macro-paths:
  - "macros"

test-paths:
  - "tests"

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_btc:

    silver:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      feature_store:
        +schema: feature_store

        feature_versions:
          +materialized: table

        features:
          +materialized: incremental
          +partition_by:
            field: ts
            data_type: timestamp
            granularity: day

        labels:
          +materialized: incremental
          +partition_by:
            field: ts
            data_type: timestamp
            granularity: day