name: "dbt_btc"
version: "1.0.0"
config-version: 2

profile: "dbt_btc"

model-paths: ["models", "intermediate", "marts"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_btc:
    models:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: feature_store
      +materialized: incremental