version: 2

models:
  - name: btc_ohlcv_1m_silver
    description: "Clean BTC OHLCV candles from BigLake bronze source."

    columns:
      - name: ts
        tests:
          - not_null
          - unique

      - name: symbol
        tests:
          - not_null

      - name: timeframe
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['1m']

      - name: open_price
        tests:
          - not_null

      - name: high_price
        tests:
          - not_null

      - name: low_price
        tests:
          - not_null

      - name: close_price
        tests:
          - not_null

      - name: volume
        tests:
          - not_null

      - name: source
        tests:
          - not_null

    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "high_price >= low_price"

      - dbt_utils.expression_is_true:
          arguments:
            expression: "open_price >= 0 AND close_price >= 0"

      - dbt_utils.expression_is_true:
          arguments:
            expression: "volume >= 0"