version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: ohlcv_btc
        description: "Raw BTC OHLCV candles from market APIs"
        columns:
          - name: symbol
            tests:
              - not_null
          - name: ts
            tests:
              - not_null
          - name: timeframe
            tests:
              - not_null
          - name: close_price
            tests:
              - not_null
          - name: volume
            tests:
              - not_null