version: 2

sources:
  - name: biglake_bronze
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BQ_DATASET') }}"
    tables:
      - name: btc_ohlcv_1m_bronze
        description: "BigLake external table over BTC OHLCV 1-minute Parquet files in GCS."
        columns:
          - name: open_time
            tests:
              - not_null
              - unique
          - name: close
            tests:
              - not_null
          - name: volume
            tests:
              - not_null
          - name: symbol
            tests:
              - not_null